In [1]:
###remove case sensitivity
#input file is ds.csv

import hashlib

'''
hashlib.md5('heroine'.encode()).hexdigest()
hashlib.sha256('poftutcom'.encode()).hexdigest()
hashlib.sha512('poftutcom'.encode()).hexdigest()


to do hashing in group, you can use the following command
for h in map(hashlib.sha256,['poftut.com'.encode(),'ismail'.encode(),'ali'.encode()]):
 h.hexdigest()
'''

countries = ['India',
'China',
'Pakistan',
'Bangladesh',
'Afghanistan']

events=['Civil unrest',
'Attack',
'Disease outbreak',
'Flood']

months=['January',
'February',
'March',
'April',
'May',
'June',
'July',
'August',
'September',
'October',
'November',
'December']
#Provinces of Pakistan
provincePak= ['Sindh',
'Punjab',
'Balochistan',
'Khyber Pakhtunkhwa',
'Gilgit Baltistan',
'Azad Kashmir',
'Islamabad']
#Provinces of China:

provinceChina=['Qinghai',
'Sichuan',
'Gansu',
'Heilongjiang',
'Yunnan',
'Hunan',
'Shaanxi',
'Hebei',
'Jilin',
'Hubei',
'Hubei',
'Guizhou',
'Guangdong',
'Jiangxi',
'Henan',
'Shanxi',
'Shandong',
'Liaoning',
'Anhui',
'Fujian',
'Jiangsu',
'Zhejiang',
'Taiwan',
'Hainan',
'Hong Kong',
'Tibet',
'Beijing',
'Xinjiang',
'Suzhou']

provinceIndia =['Andhra Pradesh',
                'Arunachal Pradesh',
                'Assam',
                'Bihar',
                'Chhattisgarh',
                'Goa',
                'Gujarat',
                'Haryana',
                'Himachal Pradesh',
                'Jharkhand',
                'Karnataka',
                'Kerala',
                'Madhya Pradesh',
                'Maharashtra',
                'Manipur',
                'Meghalaya',
                'Mizoram',
                'Nagaland',
                'Odisha',
                'Punjab',
                'Rajasthan',
                'Sikkim',
                'Tamil Nadu',
                'Telangana',
                'Tripura',
                'Uttar Pradesh',
                'Uttarakhand',
                'West Bengal',
                'Andaman and Nicobar Islands',
                'Chandigarh',
                'Dadra & Nagar Haveli and Daman & Diu',
                'Delhi',
                'Kashmir',#
                'Lakshadweep',
                'Puducherry',
                'Ladakh']



In [2]:
dCountries = {}
dEvents = {}
dProvincePak = {}
dProvinceChina = {}
dProvinceIndia = {}
dMonths = {}

for a in countries:
    dCountries[a] = int(hashlib.sha512(a.encode()).hexdigest()[0:10], 16)
    
for a in months:
    dMonths[a] = int(hashlib.sha512(a.encode()).hexdigest()[0:10], 16)
    
for a in events:
    dEvents[a] = int(hashlib.sha512(a.encode()).hexdigest()[0:10], 16)
    
for a in provincePak:
    dProvincePak[a] = int(hashlib.sha512(a.encode()).hexdigest()[0:10], 16)
    
for a in provinceChina:
    dProvinceChina[a] = int(hashlib.sha512(a.encode()).hexdigest()[0:10], 16)

for a in provinceIndia:
    dProvinceIndia[a] = int(hashlib.sha512(a.encode()).hexdigest()[0:10], 16)
    

#merging dictionaries for province
dProvince = {**dProvincePak, **dProvinceChina, **dProvinceIndia}

In [3]:
dCountries,dEvents,dMonths, dProvince

({'India': 599540218941,
  'China': 922074254021,
  'Pakistan': 805650366791,
  'Bangladesh': 550924169409,
  'Afghanistan': 796255062975},
 {'Civil unrest': 842955241147,
  'Attack': 173815961506,
  'Disease outbreak': 782389966709,
  'Flood': 504567342880},
 {'January': 789269779534,
  'February': 898528197691,
  'March': 341814020434,
  'April': 582981880659,
  'May': 881714492924,
  'June': 842191546849,
  'July': 225044240400,
  'August': 637860132779,
  'September': 327893498858,
  'October': 81113368858,
  'November': 715105976379,
  'December': 321193061305},
 {'Sindh': 1083570781771,
  'Punjab': 115979017587,
  'Balochistan': 491896530011,
  'Khyber Pakhtunkhwa': 397587297653,
  'Gilgit Baltistan': 405405895484,
  'Azad Kashmir': 73319429031,
  'Islamabad': 523233326767,
  'Qinghai': 160138371888,
  'Sichuan': 623798892277,
  'Gansu': 275418627945,
  'Heilongjiang': 874060229648,
  'Yunnan': 1081167887854,
  'Hunan': 1026562091902,
  'Shaanxi': 137576383028,
  'Hebei': 7700668

In [4]:
def getEvent(val): 
    for key, value in dEvents.items(): 
         if val == value: 
             return key
def getCountry(val): 
    for key, value in dCountries.items(): 
         if val == value: 
             return key
def getMonth(val): 
    for key, value in dMonths.items(): 
         if val == value: 
             return key
def getProvince(val): 
    for key, value in dProvince.items(): 
         if val == value: 
             return key

In [5]:
import csv
filename = "dataset.xls"#-------------------------INPUT



In [6]:
fields = []
rows = []

with open(filename, 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    
    fields = next(csvreader)
    
    for row in csvreader:
        rows.append(row)

In [7]:
rows

[['India', '2020', 'February', 'Civil unrest', 'Delhi'],
 ['India', '2017', 'August', 'Civil unrest', 'Haryana'],
 ['India', '2013', 'August', 'Civil unrest', 'Uttar Pradesh'],
 ['India', '2006', 'May', 'Civil unrest', 'Gujarat'],
 ['India', '2002', 'February', 'Civil unrest', 'Gujarat'],
 ['India', '2003', 'February', 'Civil unrest', 'Assam'],
 ['India', '2011', 'April', 'Civil unrest', 'Delhi'],
 ['India', '2015', 'June', 'Civil unrest', 'Delhi'],
 ['India', '2014', 'September', 'Civil unrest', 'West Bengal'],
 ['India', '2016', 'February', 'Civil unrest', 'Haryana'],
 ['India', '2018', 'August', 'Flood', 'Kerala'],
 ['India', '2017', 'August', 'Flood', 'Maharashtra'],
 ['India', '2017', 'July', 'Flood', 'Gujarat'],
 ['India', '2017', 'July', 'Flood', 'West Bengal'],
 ['India', '2017', 'August', 'Flood', 'Bihar'],
 ['India', '2017', 'July', 'Flood', 'Assam'],
 ['India', '2016', 'July', 'Flood', 'Assam'],
 ['India', '2015', 'November', 'Flood', 'Tamil Nadu'],
 ['India', '2015', 'June'

In [8]:
hashRows = []
for country, year, month, event, province in rows:
    hashRows.append([ str(dCountries[country]), year, str(dMonths[month]), str(dEvents[event]), str(dProvince[province]) ])

In [9]:
hashRows

[['599540218941', '2020', '898528197691', '842955241147', '611572722954'],
 ['599540218941', '2017', '637860132779', '842955241147', '437800888172'],
 ['599540218941', '2013', '637860132779', '842955241147', '722918171141'],
 ['599540218941', '2006', '881714492924', '842955241147', '124006097873'],
 ['599540218941', '2002', '898528197691', '842955241147', '124006097873'],
 ['599540218941', '2003', '898528197691', '842955241147', '529774963214'],
 ['599540218941', '2011', '582981880659', '842955241147', '611572722954'],
 ['599540218941', '2015', '842191546849', '842955241147', '611572722954'],
 ['599540218941', '2014', '327893498858', '842955241147', '467736529324'],
 ['599540218941', '2016', '898528197691', '842955241147', '437800888172'],
 ['599540218941', '2018', '637860132779', '504567342880', '338534963061'],
 ['599540218941', '2017', '637860132779', '504567342880', '775392800431'],
 ['599540218941', '2017', '225044240400', '504567342880', '124006097873'],
 ['599540218941', '2017',

In [10]:
filename2 = "dsHash2.csv"
with open(filename2, 'w') as csvfile2:
    csvwriter = csv.writer(csvfile2, delimiter=',', lineterminator='\r')
    csvwriter.writerow(fields)
    csvwriter.writerows(hashRows)

In [11]:
filename2

'dsHash2.csv'

In [12]:
csvfile.close()
csvfile2.close()

In [13]:
fields = []
rows2 = []
filename = "dsHash2.csv"
with open(filename, 'r', encoding = 'utf-8') as csvfile:
    csvreader = csv.reader(csvfile)
    
    fields = next(csvreader)
    
    for row in csvreader:
        rows2.append(row)

In [14]:
rows2

[['599540218941', '2020', '898528197691', '842955241147', '611572722954'],
 ['599540218941', '2017', '637860132779', '842955241147', '437800888172'],
 ['599540218941', '2013', '637860132779', '842955241147', '722918171141'],
 ['599540218941', '2006', '881714492924', '842955241147', '124006097873'],
 ['599540218941', '2002', '898528197691', '842955241147', '124006097873'],
 ['599540218941', '2003', '898528197691', '842955241147', '529774963214'],
 ['599540218941', '2011', '582981880659', '842955241147', '611572722954'],
 ['599540218941', '2015', '842191546849', '842955241147', '611572722954'],
 ['599540218941', '2014', '327893498858', '842955241147', '467736529324'],
 ['599540218941', '2016', '898528197691', '842955241147', '437800888172'],
 ['599540218941', '2018', '637860132779', '504567342880', '338534963061'],
 ['599540218941', '2017', '637860132779', '504567342880', '775392800431'],
 ['599540218941', '2017', '225044240400', '504567342880', '124006097873'],
 ['599540218941', '2017',

In [15]:
getCountry(599540218941)

'India'

In [16]:
#Now training the model using training data---------------------------------------------------#

In [17]:
import pandas as pd
import numpy as np
df=pd.read_csv("dsHash2.csv")
from sklearn.model_selection import train_test_split


In [18]:
df

Country  Year         Month         Event  State/Province
0    599540218941  2020  898528197691  842955241147    611572722954
1    599540218941  2017  637860132779  842955241147    437800888172
2    599540218941  2013  637860132779  842955241147    722918171141
3    599540218941  2006  881714492924  842955241147    124006097873
4    599540218941  2002  898528197691  842955241147    124006097873
..            ...   ...           ...           ...             ...
139  805650366791  2010  225044240400  504567342880    491896530011
140  805650366791  2010  225044240400  504567342880    405405895484
141  805650366791  2010  225044240400  504567342880    115979017587
142  805650366791  2019  327893498858  504567342880    397587297653
143  805650366791  2017  637860132779  504567342880   1083570781771

[144 rows x 5 columns]

In [19]:
#df.Country.astype(int)
df['State/Province']

0       611572722954
1       437800888172
2       722918171141
3       124006097873
4       124006097873
           ...      
139     491896530011
140     405405895484
141     115979017587
142     397587297653
143    1083570781771
Name: State/Province, Length: 144, dtype: int64

In [20]:
x=df[['Country','Year','Month','State/Province']]
y=df['Event']

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 0)

In [22]:
#predicting result using decision tree &
#predicting result using KNN, Naive Bayes
from sklearn import datasets 
from sklearn.metrics import confusion_matrix 


#1. Decision Tree -----------------------------
from sklearn.tree import DecisionTreeClassifier
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(x_train, y_train)
#predicting
dtree_predictions = dtree_model.predict(x_test)


# creating a confusion matrix 
cm = confusion_matrix(y_test, dtree_predictions) 

In [23]:
dtree_predictions

array([173815961506, 842955241147, 173815961506, 173815961506,
       173815961506, 504567342880, 173815961506, 842955241147,
       504567342880, 173815961506, 842955241147, 173815961506,
       842955241147, 842955241147, 504567342880, 173815961506,
       173815961506, 173815961506, 173815961506, 842955241147,
       842955241147, 173815961506, 173815961506, 842955241147,
       842955241147, 173815961506, 173815961506, 842955241147,
       173815961506, 173815961506, 173815961506, 173815961506,
       842955241147, 504567342880, 173815961506, 173815961506],
      dtype=int64)

In [24]:
cm#Dtree Confusion matrix

array([[10,  0,  0,  1],
       [ 5,  2,  0,  3],
       [ 4,  0,  0,  4],
       [ 2,  2,  0,  3]], dtype=int64)

In [25]:
# predicting result using KNN--------------------

# training a KNN classifier 
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 7).fit(x_train, y_train) 
  
# accuracy on X_test 
accuracy = knn.score(x_test, y_test) 
#print (accuracy) 
  
# creating a confusion matrix 
knn_predictions = knn.predict(x_test)  
cm = confusion_matrix(y_test, knn_predictions) 

accuracy#Accuracy using KNN

0.19444444444444445

In [26]:
cm#KNN Confusion matrix

array([[2, 6, 1, 2],
       [5, 4, 0, 1],
       [4, 2, 1, 1],
       [3, 4, 0, 0]], dtype=int64)

In [27]:
# predicting result using Naive Bayes----------------

# training a Naive Bayes classifier 
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(x_train, y_train) 
gnb_predictions = gnb.predict(x_test)

In [28]:
# accuracy on X_test 
accuracy = gnb.score(x_test, y_test)  
# creating a confusion matrix 
cm = confusion_matrix(y_test, gnb_predictions) 

accuracy#Accuracy using Naive Bayes

0.2222222222222222

In [29]:
cm#Naive Bayes Confusion matrix

array([[4, 3, 3, 1],
       [9, 1, 0, 0],
       [5, 2, 1, 0],
       [4, 1, 0, 2]], dtype=int64)

In [30]:
#1. DT
def predictDTree(country, year, month, province):
    result = dtree_model.predict([ [dCountries[country], 2020, dMonths[month], dProvince[province] ] ])
    return getEvent(result)

a = predictDTree('India', 2020, 'June', 'Maharashtra')

In [31]:
def predictKNN(country, year, month, province):
    result = knn.predict([ [dCountries[country], 2020, dMonths[month], dProvince[province] ] ])
    return getEvent(result)

b = predictKNN('India', 2020, 'June', 'West Bengal')

In [32]:
def predictGNB(country, year, month, province):
    result = gnb.predict([ [dCountries[country], 2020, dMonths[month], dProvince[province] ] ])
    return getEvent(result)
c = predictGNB('India', 2020, 'June', 'Odisha')

In [33]:
a, b, c

('Attack', 'Civil unrest', 'Attack')